# ESTADÍSTICA APLICADA #
## ANDREA CAROLINA LÓPEZ RUIZ ##
**26 ENERO - SESIÓN  2**

In [23]:
pip install yfinance

In [24]:
import yfinance as yf

In [25]:
import numpy as np

In [26]:
edades = [12,18,25,32,40]

In [27]:
type(edades)

list

In [68]:
np.array(edades)

array([12, 18, 25, 32, 40])

In [29]:
np.mean(edades)

25.4

In [30]:
np.prod(edades)

6912000

In [31]:
np.var(edades)

98.24000000000001

In [32]:
np.var(edades,ddof=1)

122.80000000000001

In [33]:
np.std(edades)

9.911609354691095

In [34]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [37]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.ones(3)

array([1., 1., 1.])

In [40]:
#random int numbers
np.random.randint(0,25,10)

array([20, 20,  1,  9, 19, 13, 14, 13, 13, 22])

In [43]:
np.random.seed(15)
np.random.randint(0,25,10)

array([ 8, 21, 12,  5, 23,  0,  7, 11, 21, 22])

In [45]:
np.random.seed(15)
random = np.random.randint(0,25,10)

In [47]:
random

array([ 8, 21, 12,  5, 23,  0,  7, 11, 21, 22])

In [48]:
np.sort (random)

array([ 0,  5,  7,  8, 11, 12, 21, 21, 22, 23])

In [50]:
random=np.sort (random)

In [51]:
random

array([ 0,  5,  7,  8, 11, 12, 21, 21, 22, 23])

In [52]:
#python empieza en 0
random[3]

8

In [53]:
random [[3,5]]

array([ 8, 12])

In [54]:
random >5

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [56]:
random[random>5]

array([ 7,  8, 11, 12, 21, 21, 22, 23])

In [59]:
numbers = [1.58,12.4373774,7858.3483784]
numbers=np.array(numbers)

In [61]:
#función 
np.mean(numbers)

2624.1219186000003

In [62]:
#Método
numbers.mean()

2624.1219186000003

In [63]:
round(np.mean(np.array(numbers)))

2624

In [65]:
np.array(numbers).mean().round(2)

2624.12

In [66]:
numbers.mean().round(2)

2624.12